# Generated by Django 2.1.4 on 2018-12-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('arrived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.EmailField(blank=True, max_length=200, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('membership_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('pay_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('direct_debit', 'Direct Debit'), ('transfer', 'Transfer'), ('better_place', 'BetterPlace')], max_length=200, null=True)),
                ('frequent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.FrequentContribution')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='frequent_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.FrequentContribution'),
        ),
        migrations.AddField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Member'),
        ),
    ]
