# Generated by Django 2.1.4 on 2018-12-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='frequent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.FrequentContribution'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('direct_debit', 'Direct Debit'), ('transfer', 'Transfer'), ('better_place', 'BetterPlace')], max_length=200, null=True),
        ),
    ]
