# Generated by Django 2.1.4 on 2018-12-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20181224_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('period', models.DurationField()),
                ('direct_debit', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='monthlycontribution',
            name='member',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='monthly_contribution',
        ),
        migrations.DeleteModel(
            name='MonthlyContribution',
        ),
        migrations.AddField(
            model_name='donation',
            name='frequent_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.FrequentContribution'),
        ),
    ]
