# Generated by Django 2.1.4 on 2019-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190105_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.CharField(choices=[('voting', 'Voting Membership'), ('supporting', 'Supporting Membership'), ('none', 'None')], default='none', max_length=200),
            preserve_default=False,
        ),
    ]
