# Generated by Django 2.1.4 on 2018-12-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20181224_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentcontribution',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='frequent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.FrequentContribution'),
        ),
    ]
