# Generated by Django 2.1.4 on 2018-12-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20181224_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentcontribution',
            name='name',
            field=models.CharField(default='unnamed', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='frequent_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.FrequentContribution'),
        ),
    ]
