# Generated by Django 2.1.4 on 2018-12-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20181224_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentcontribution',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='frequentcontribution',
            name='direct_debit',
        ),
        migrations.RemoveField(
            model_name='frequentcontribution',
            name='period',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('direct_debit', 'Direct Debit'), ('transfer', 'Transfer'), ('better_place', 'BetterPlace')], default='direct_debit', max_length=200),
            preserve_default=False,
        ),
    ]
